# Sorting, Counting, Subsetting

## Import libraries

In [1]:
## import libraries
import pandas as pd

## Upload Olympics datasets to this notebook.

### Import ```olympics-summer.csv``` and store in a dataframe called ```dfs``` (<a href="https://raw.githubusercontent.com/sandeepmj/datasets/main/olympics-summer.csv">link</a>).


### Import ```olympics-winter.csv``` and store in a dataframe called ```dfw``` (<a href="https://raw.githubusercontent.com/sandeepmj/datasets/main/olympics-winter.csv">link</a>).

In [2]:
## import summer data
dfs = pd.read_csv("https://raw.githubusercontent.com/sandeepmj/datasets/main/olympics-summer.csv")
dfs

,ID,Athlete Name,Sex,Age,Height,Weight,Team,NOC,Year,City,Sport,Event,Medal
0,1724,Aristidis Akratopoulos,M,NaN,NaN,NaN,Greece,GRE,1896,Athina,Tennis,Tennis Men's Singles,NaN
1,1724,Aristidis Akratopoulos,M,NaN,NaN,NaN,Greece-3,GRE,1896,Athina,Tennis,Tennis Men's Doubles,NaN
2,1725,"Konstantinos ""Kostas"" Akratopoulos",M,NaN,NaN,NaN,Greece,GRE,1896,Athina,Tennis,Tennis Men's Singles,NaN
3,1725,"Konstantinos ""Kostas"" Akratopoulos",M,NaN,NaN,NaN,Greece-3,GRE,1896,Athina,Tennis,Tennis Men's Doubles,NaN
4,4113,Anastasios Andreou,M,NaN,NaN,NaN,Greece,GRE,1896,Athina,Athletics,Athletics Men's 110 metres Hurdles,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
222547,135528,Marc Zwiebler,M,32.0,181.0,75.0,Germany,GER,2016,Rio de Janeiro,Badminton,Badminton Men's Singles,NaN
222548,135547,Viktoriya Viktorovna Zyabkina,F,23.0,174.0,62.0,Kazakhstan,KAZ,2016,Rio de Janeiro,Athletics,Athletics Women's 100 metres,NaN
222549,135547,Viktoriya Viktorovna Zyabkina,F,23.0,174.0,62.0,Kazakhstan,KAZ,2016,Rio de Janeiro,Athletics,Athletics Women's 200 metres,NaN
222550,135547,Viktoriya Viktorovna Zyabkina,F,23.0,174.0,62.0,Kazakhstan,KAZ,2016,Rio de Janeiro,Athletics,Athletics Women's 4 x 100 metres Relay,NaN
222551,135568,Olga Igorevna Zyuzkova,F,33.0,171.0,69.0,Belarus,BLR,2016,Rio de Janeiro,Basketball,Basketball Women's Basketball,NaN

In [64]:
## import winter data
dfw = pd.read_csv("https://raw.githubusercontent.com/sandeepmj/datasets/main/olympics-winter.csv")
dfw

,ID,Athlete Name,Sex,Age,Height,Weight,Team,NOC,Year,City,Sport,Event,Medal
0,391,Clarence John Abel,M,23.0,185.0,102.0,United States,USA,1924,Chamonix,Ice Hockey,Ice Hockey Men's Ice Hockey,Silver
1,992,Josef Adolf,M,25.0,NaN,NaN,Czechoslovakia,TCH,1924,Chamonix,Nordic Combined,Nordic Combined Men's Individual,NaN
2,1077,Xavier Affentranger,M,26.0,NaN,NaN,Switzerland,SUI,1924,Chamonix,Ski Jumping,"Ski Jumping Men's Normal Hill, Individual",NaN
3,1077,Xavier Affentranger,M,26.0,NaN,NaN,Switzerland,SUI,1924,Chamonix,Cross Country Skiing,Cross Country Skiing Men's 18 kilometres,NaN
4,1077,Xavier Affentranger,M,26.0,NaN,NaN,Switzerland,SUI,1924,Chamonix,Nordic Combined,Nordic Combined Men's Individual,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
48559,135485,Stepan Olegovich Zuyev,M,25.0,189.0,90.0,Russia,RUS,2014,Sochi,Alpine Skiing,Alpine Skiing Men's Slalom,NaN
48560,135500,Kristaps Zvejnieks,M,21.0,185.0,87.0,Latvia,LAT,2014,Sochi,Alpine Skiing,Alpine Skiing Men's Giant Slalom,NaN
48561,135500,Kristaps Zvejnieks,M,21.0,185.0,87.0,Latvia,LAT,2014,Sochi,Alpine Skiing,Alpine Skiing Men's Slalom,NaN
48562,135570,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Individual",NaN
48563,135570,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Team",NaN

## Get a sense of the data

In [4]:
## SUMMER
## what exactly do we have: columns, datatypes, etc.
dfs.info()

<class 'pandas.DataFrame'>
RangeIndex: 222552 entries, 0 to 222551
Data columns (total 13 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   ID            222552 non-null  int64
 1   Athlete Name  222552 non-null  str
 2   Sex           222552 non-null  str
 3   Age           213363 non-null  float64
 4   Height        170695 non-null  float64
 5   Weight        168698 non-null  float64
 6   Team          222552 non-null  str
 7   NOC           222552 non-null  str
 8   Year          222552 non-null  int64
 9   City          222552 non-null  str
 10  Sport         222552 non-null  str
 11  Event         222552 non-null  str
 12  Medal         34088 non-null   str
dtypes: float64(3), int64(2), str(8)
memory usage: 22.1 MB

In [5]:
## WINTER
## what exactly do we have: columns, datatypes, etc.
dfw.info()

<class 'pandas.DataFrame'>
RangeIndex: 48564 entries, 0 to 48563
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   ID            48564 non-null  int64
 1   Athlete Name  48564 non-null  str
 2   Sex           48564 non-null  str
 3   Age           48279 non-null  float64
 4   Height        40250 non-null  float64
 5   Weight        39543 non-null  float64
 6   Team          48564 non-null  str
 7   NOC           48564 non-null  str
 8   Year          48564 non-null  int64
 9   City          48564 non-null  str
 10  Sport         48564 non-null  str
 11  Event         48564 non-null  str
 12  Medal         5695 non-null   str
dtypes: float64(3), int64(2), str(8)
memory usage: 4.8 MB

## Subsetting dataframes into smaller, targeted dataframes

When you subset a dataframe, you are filtering down based on selecting specific columns. We want to winnow a large dataset to manageable size by including only relevant columns.

There are two ways of doing this. One simple method is very common (you'll see many people use it), but the other method (also simple) is way more powerful and flexible.

### Method 1 - Pass a list of multiple column headers, it returns dataframe with only those columns
This is like calling a series (```df["Year"]```), but multiple columns:

####  ```df[["Column 1", "Column 2"]]```

In [6]:
## Create a dataframe that for only summer games years and cities
dfs_yr_city = dfs[["Year", "City"]]
dfs_yr_city

        Year            City
0       1896          Athina
1       1896          Athina
2       1896          Athina
3       1896          Athina
4       1896          Athina
...      ...             ...
222547  2016  Rio de Janeiro
222548  2016  Rio de Janeiro
222549  2016  Rio de Janeiro
222550  2016  Rio de Janeiro
222551  2016  Rio de Janeiro

[222552 rows x 2 columns]

## Sorting by single value

```dataframe.sort_values(by="Value 1", ascending = True)``` for A-Z or smaller numbers to bigger numbers

```ascending = False``` for Z-A or bigger to smaller numbers.

In [7]:
## sort by athlete names A-Z for winter olympics
dfw.sort_values(by="Athlete Name", ascending = True)

,ID,Athlete Name,Sex,Age,Height,Weight,Team,NOC,Year,City,Sport,Event,Medal
2788,56427,Aage Justesen,M,30.0,NaN,NaN,Denmark,DEN,1948,Sankt Moritz,Speed Skating,Speed Skating Men's 500 metres,NaN
15974,13348,"Aaltje Grietje ""Alie"" Boorsma",F,24.0,179.0,75.0,Netherlands,NED,1984,Sarajevo,Speed Skating,Speed Skating Women's 500 metres,NaN
15975,13348,"Aaltje Grietje ""Alie"" Boorsma",F,24.0,179.0,75.0,Netherlands,NED,1984,Sarajevo,Speed Skating,"Speed Skating Women's 1,000 metres",NaN
3799,49758,Aarne Vin Edward Honkavaara,M,27.0,184.0,81.0,Finland,FIN,1952,Oslo,Ice Hockey,Ice Hockey Men's Ice Hockey,NaN
44053,12407,Aaron Blunck,M,17.0,180.0,78.0,United States,USA,2014,Sochi,Freestyle Skiing,Freestyle Skiing Men's Halfpipe,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
15622,122902,yvind Tveter,M,25.0,190.0,89.0,Norway,NOR,1980,Lake Placid,Speed Skating,"Speed Skating Men's 5,000 metres",NaN
15623,122902,yvind Tveter,M,25.0,190.0,89.0,Norway,NOR,1980,Lake Placid,Speed Skating,"Speed Skating Men's 10,000 metres",NaN
8706,5787,zer Atei,M,25.0,180.0,72.0,Turkey,TUR,1968,Grenoble,Alpine Skiing,Alpine Skiing Men's Slalom,NaN
8705,5787,zer Atei,M,25.0,180.0,72.0,Turkey,TUR,1968,Grenoble,Alpine Skiing,Alpine Skiing Men's Giant Slalom,NaN
8704,5787,zer Atei,M,25.0,180.0,72.0,Turkey,TUR,1968,Grenoble,Alpine Skiing,Alpine Skiing Men's Downhill,NaN

In [8]:
## sort city z-a
dfw.sort_values(by="City", ascending = False)

,ID,Athlete Name,Sex,Age,Height,Weight,Team,NOC,Year,City,Sport,Event,Medal
39561,11951,Ole Einar Bjrndalen,M,36.0,178.0,65.0,Norway,NOR,2010,Vancouver,Biathlon,Biathlon Men's 4 x 7.5 kilometres Relay,Gold
40747,52463,Marc Iselin,M,29.0,178.0,83.0,Switzerland,SUI,2010,Vancouver,Snowboarding,Snowboarding Men's Parallel Giant Slalom,NaN
40741,52316,Dmitry Gennadyevich Ipatov,M,25.0,176.0,60.0,Russia,RUS,2010,Vancouver,Ski Jumping,"Ski Jumping Men's Large Hill, Team",NaN
40742,52345,"Michael James Grant ""Mike"" Ireland",M,36.0,181.0,79.0,Canada,CAN,2010,Vancouver,Speed Skating,Speed Skating Men's 500 metres,NaN
40743,52392,Haley Lyn Irwin,F,21.0,170.0,78.0,Canada,CAN,2010,Vancouver,Ice Hockey,Ice Hockey Women's Ice Hockey,Gold
...,...,...,...,...,...,...,...,...,...,...,...,...,...
22495,75068,Dennis Edward Marineau,M,29.0,172.0,81.0,Canada-2,CAN,1992,Albertville,Bobsleigh,Bobsleigh Men's Two,NaN
22494,74979,Diego Margozzini,M,21.0,182.0,76.0,Chile,CHI,1992,Albertville,Alpine Skiing,Alpine Skiing Men's Giant Slalom,NaN
22493,74960,Pascal Margerit,M,20.0,180.0,75.0,France,FRA,1992,Albertville,Ice Hockey,Ice Hockey Men's Ice Hockey,NaN
22492,74931,Alexander Marent,M,22.0,168.0,68.0,Austria,AUT,1992,Albertville,Cross Country Skiing,Cross Country Skiing Men's 4 x 10 kilometres R...,NaN
21917,53932,Pawe Julian Jaroszek,M,20.0,185.0,82.0,Poland,POL,1992,Albertville,Speed Skating,"Speed Skating Men's 1,500 metres",NaN

## Sorting by multiple values

```dataframe.sort_values(by=["Value 1", "Value 2"], ascending = True)``` for A-Z or smaller numbers to bigger numbers

```ascending = False``` for Z-A or bigger to smaller numbers.

In [9]:
## Sort by values (City and Year) for winter olympics
dfw_city_year_sort = dfw.sort_values(by=["City", "Year"], ascending = True)
dfw_city_year_sort.tail(10000)

,ID,Athlete Name,Sex,Age,Height,Weight,Team,NOC,Year,City,Sport,Event,Medal
48464,133887,Andreas ampa,M,20.0,168.0,70.0,Slovakia,SVK,2014,Sochi,Alpine Skiing,Alpine Skiing Men's Super G,NaN
48465,133887,Andreas ampa,M,20.0,168.0,70.0,Slovakia,SVK,2014,Sochi,Alpine Skiing,Alpine Skiing Men's Giant Slalom,NaN
48466,133887,Andreas ampa,M,20.0,168.0,70.0,Slovakia,SVK,2014,Sochi,Alpine Skiing,Alpine Skiing Men's Slalom,NaN
48467,133939,Zang Jialiang,M,26.0,175.0,70.0,China,CHN,2014,Sochi,Curling,Curling Men's Curling,NaN
48468,133942,Thomas Zangerl,M,30.0,181.0,81.0,Austria,AUT,2014,Sochi,Freestyle Skiing,Freestyle Skiing Men's Ski Cross,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
43668,135492,Veronika Zuzulov (-Velez),F,25.0,172.0,72.0,Slovakia,SVK,2010,Vancouver,Alpine Skiing,Alpine Skiing Women's Giant Slalom,NaN
43669,135492,Veronika Zuzulov (-Velez),F,25.0,172.0,72.0,Slovakia,SVK,2010,Vancouver,Alpine Skiing,Alpine Skiing Women's Slalom,NaN
43670,135496,Veronika Zvaiov,F,21.0,176.0,62.0,Czech Republic,CZE,2010,Vancouver,Biathlon,Biathlon Women's 7.5 kilometres Sprint,NaN
43671,135500,Kristaps Zvejnieks,M,17.0,185.0,87.0,Latvia,LAT,2010,Vancouver,Alpine Skiing,Alpine Skiing Men's Giant Slalom,NaN
43672,135500,Kristaps Zvejnieks,M,17.0,185.0,87.0,Latvia,LAT,2010,Vancouver,Alpine Skiing,Alpine Skiing Men's Slalom,NaN

In [10]:
## sort by year and then city
dfw_year_city_sort = dfw.sort_values(by=["Year", "City"], ascending = True)
dfw_year_city_sort.tail(1000)

,ID,Athlete Name,Sex,Age,Height,Weight,Team,NOC,Year,City,Sport,Event,Medal
47564,109922,Mariya Igorevna Shkanova,F,24.0,166.0,66.0,Belarus,BLR,2014,Sochi,Alpine Skiing,Alpine Skiing Women's Super G,NaN
47565,109922,Mariya Igorevna Shkanova,F,24.0,166.0,66.0,Belarus,BLR,2014,Sochi,Alpine Skiing,Alpine Skiing Women's Giant Slalom,NaN
47566,109922,Mariya Igorevna Shkanova,F,24.0,166.0,66.0,Belarus,BLR,2014,Sochi,Alpine Skiing,Alpine Skiing Women's Slalom,NaN
47567,109925,Olena Shkhumova,F,20.0,178.0,87.0,Ukraine,UKR,2014,Sochi,Luge,Luge Women's Singles,NaN
47568,109925,Olena Shkhumova,F,20.0,178.0,87.0,Ukraine,UKR,2014,Sochi,Luge,Luge Mixed Team Relay,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
48559,135485,Stepan Olegovich Zuyev,M,25.0,189.0,90.0,Russia,RUS,2014,Sochi,Alpine Skiing,Alpine Skiing Men's Slalom,NaN
48560,135500,Kristaps Zvejnieks,M,21.0,185.0,87.0,Latvia,LAT,2014,Sochi,Alpine Skiing,Alpine Skiing Men's Giant Slalom,NaN
48561,135500,Kristaps Zvejnieks,M,21.0,185.0,87.0,Latvia,LAT,2014,Sochi,Alpine Skiing,Alpine Skiing Men's Slalom,NaN
48562,135570,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Individual",NaN
48563,135570,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Team",NaN

In [11]:
## sort by city and year but descending for summer games
dfs_city_year_d_sort = dfs.sort_values(by=["City", "Year"], ascending = False)
dfs_city_year_d_sort.tail(1000)

,ID,Athlete Name,Sex,Age,Height,Weight,Team,NOC,Year,City,Sport,Event,Medal
26008,111782,Josip krabl,M,25.0,NaN,NaN,Yugoslavia,YUG,1928,Amsterdam,Cycling,"Cycling Men's Road Race, Individual",NaN
26009,111782,Josip krabl,M,25.0,NaN,NaN,Yugoslavia,YUG,1928,Amsterdam,Cycling,"Cycling Men's Road Race, Team",NaN
26010,111924,Janusz Lubomir lzak,M,21.0,191.0,95.0,Poland,POL,1928,Amsterdam,Rowing,Rowing Men's Coxed Eights,NaN
26011,111934,Ludomir Slendziski,M,38.0,NaN,NaN,Poland,POL,1928,Amsterdam,Art Competitions,"Art Competitions Mixed Painting, Paintings",NaN
26012,111944,Franz Theodor Max Slevogt,M,59.0,NaN,NaN,Germany,GER,1928,Amsterdam,Art Competitions,"Art Competitions Mixed Painting, Graphic Arts",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
27003,135426,Max Zumstein,M,NaN,NaN,NaN,Switzerland,SUI,1928,Amsterdam,Hockey,Hockey Men's Hockey,NaN
27004,135435,Faelo Ziga,M,NaN,NaN,NaN,Chile,CHI,1928,Amsterdam,Swimming,Swimming Men's 100 metres Freestyle,NaN
27005,135499,Alberts Zvejnieks,M,25.0,NaN,NaN,Latvia,LAT,1928,Amsterdam,Wrestling,"Wrestling Men's Heavyweight, Greco-Roman",NaN
27006,135552,Jan (Johann-) Zybert (Siebert-),M,20.0,NaN,NaN,Poland,POL,1928,Amsterdam,Cycling,"Cycling Men's Team Pursuit, 4,000 metres",NaN
27007,135561,Frantiek Zyka,M,26.0,NaN,NaN,Czechoslovakia,TCH,1928,Amsterdam,Athletics,Athletics Men's Marathon,NaN

In [12]:
## you can store into a new df

## Please don't open till instructed

### Should Winter and Summer data remain separate?

### What if we want to know total gold medals for any country?

### But if we combine them, how to we easily distinguish between summer and winter?

### Creating a new column with a default value

In [13]:
## In the summer dataframe, add "Season" column with the value "Summer"
dfs["Season"] = "summer"
dfs

,ID,Athlete Name,Sex,Age,Height,Weight,Team,NOC,Year,City,Sport,Event,Medal,Season
0,1724,Aristidis Akratopoulos,M,NaN,NaN,NaN,Greece,GRE,1896,Athina,Tennis,Tennis Men's Singles,NaN,summer
1,1724,Aristidis Akratopoulos,M,NaN,NaN,NaN,Greece-3,GRE,1896,Athina,Tennis,Tennis Men's Doubles,NaN,summer
2,1725,"Konstantinos ""Kostas"" Akratopoulos",M,NaN,NaN,NaN,Greece,GRE,1896,Athina,Tennis,Tennis Men's Singles,NaN,summer
3,1725,"Konstantinos ""Kostas"" Akratopoulos",M,NaN,NaN,NaN,Greece-3,GRE,1896,Athina,Tennis,Tennis Men's Doubles,NaN,summer
4,4113,Anastasios Andreou,M,NaN,NaN,NaN,Greece,GRE,1896,Athina,Athletics,Athletics Men's 110 metres Hurdles,NaN,summer
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
222547,135528,Marc Zwiebler,M,32.0,181.0,75.0,Germany,GER,2016,Rio de Janeiro,Badminton,Badminton Men's Singles,NaN,summer
222548,135547,Viktoriya Viktorovna Zyabkina,F,23.0,174.0,62.0,Kazakhstan,KAZ,2016,Rio de Janeiro,Athletics,Athletics Women's 100 metres,NaN,summer
222549,135547,Viktoriya Viktorovna Zyabkina,F,23.0,174.0,62.0,Kazakhstan,KAZ,2016,Rio de Janeiro,Athletics,Athletics Women's 200 metres,NaN,summer
222550,135547,Viktoriya Viktorovna Zyabkina,F,23.0,174.0,62.0,Kazakhstan,KAZ,2016,Rio de Janeiro,Athletics,Athletics Women's 4 x 100 metres Relay,NaN,summer
222551,135568,Olga Igorevna Zyuzkova,F,33.0,171.0,69.0,Belarus,BLR,2016,Rio de Janeiro,Basketball,Basketball Women's Basketball,NaN,summer

In [14]:
## In the winter dataframe, add "Season" column with the value "Winter"
dfw["Season"] = "winter"
dfw

,ID,Athlete Name,Sex,Age,Height,Weight,Team,NOC,Year,City,Sport,Event,Medal,Season
0,391,Clarence John Abel,M,23.0,185.0,102.0,United States,USA,1924,Chamonix,Ice Hockey,Ice Hockey Men's Ice Hockey,Silver,winter
1,992,Josef Adolf,M,25.0,NaN,NaN,Czechoslovakia,TCH,1924,Chamonix,Nordic Combined,Nordic Combined Men's Individual,NaN,winter
2,1077,Xavier Affentranger,M,26.0,NaN,NaN,Switzerland,SUI,1924,Chamonix,Ski Jumping,"Ski Jumping Men's Normal Hill, Individual",NaN,winter
3,1077,Xavier Affentranger,M,26.0,NaN,NaN,Switzerland,SUI,1924,Chamonix,Cross Country Skiing,Cross Country Skiing Men's 18 kilometres,NaN,winter
4,1077,Xavier Affentranger,M,26.0,NaN,NaN,Switzerland,SUI,1924,Chamonix,Nordic Combined,Nordic Combined Men's Individual,NaN,winter
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48559,135485,Stepan Olegovich Zuyev,M,25.0,189.0,90.0,Russia,RUS,2014,Sochi,Alpine Skiing,Alpine Skiing Men's Slalom,NaN,winter
48560,135500,Kristaps Zvejnieks,M,21.0,185.0,87.0,Latvia,LAT,2014,Sochi,Alpine Skiing,Alpine Skiing Men's Giant Slalom,NaN,winter
48561,135500,Kristaps Zvejnieks,M,21.0,185.0,87.0,Latvia,LAT,2014,Sochi,Alpine Skiing,Alpine Skiing Men's Slalom,NaN,winter
48562,135570,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Individual",NaN,winter
48563,135570,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Team",NaN,winter

In [15]:
## are the two column headers identical?
dfw.info()
dfs.info()

<class 'pandas.DataFrame'>
RangeIndex: 48564 entries, 0 to 48563
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   ID            48564 non-null  int64
 1   Athlete Name  48564 non-null  str
 2   Sex           48564 non-null  str
 3   Age           48279 non-null  float64
 4   Height        40250 non-null  float64
 5   Weight        39543 non-null  float64
 6   Team          48564 non-null  str
 7   NOC           48564 non-null  str
 8   Year          48564 non-null  int64
 9   City          48564 non-null  str
 10  Sport         48564 non-null  str
 11  Event         48564 non-null  str
 12  Medal         5695 non-null   str
 13  Season        48564 non-null  str
dtypes: float64(3), int64(2), str(9)
memory usage: 5.2 MB
<class 'pandas.DataFrame'>
RangeIndex: 222552 entries, 0 to 222551
Data columns (total 14 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   ID            222552 non-null  int64
 1   Athlete Name  222552 non-null  str
 2   Sex           222552 non-null  str
 3   Age           213363 non-null  float64
 4   Height        170695 non-null  float64
 5   Weight        168698 non-null  float64
 6   Team          222552 non-null  str
 7   NOC           222552 non-null  str
 8   Year          222552 non-null  int64
 9   City          222552 non-null  str
 10  Sport         222552 non-null  str
 11  Event         222552 non-null  str
 12  Medal         34088 non-null   str
 13  Season        222552 non-null  str
dtypes: float64(3), int64(2), str(9)
memory usage: 23.8 MB

In [16]:
## join winter and summer dataframes together into a dataframe called df
df = pd.concat([dfw,dfs], ignore_index = True)
df

,ID,Athlete Name,Sex,Age,Height,Weight,Team,NOC,Year,City,Sport,Event,Medal,Season
0,391,Clarence John Abel,M,23.0,185.0,102.0,United States,USA,1924,Chamonix,Ice Hockey,Ice Hockey Men's Ice Hockey,Silver,winter
1,992,Josef Adolf,M,25.0,NaN,NaN,Czechoslovakia,TCH,1924,Chamonix,Nordic Combined,Nordic Combined Men's Individual,NaN,winter
2,1077,Xavier Affentranger,M,26.0,NaN,NaN,Switzerland,SUI,1924,Chamonix,Ski Jumping,"Ski Jumping Men's Normal Hill, Individual",NaN,winter
3,1077,Xavier Affentranger,M,26.0,NaN,NaN,Switzerland,SUI,1924,Chamonix,Cross Country Skiing,Cross Country Skiing Men's 18 kilometres,NaN,winter
4,1077,Xavier Affentranger,M,26.0,NaN,NaN,Switzerland,SUI,1924,Chamonix,Nordic Combined,Nordic Combined Men's Individual,NaN,winter
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
271111,135528,Marc Zwiebler,M,32.0,181.0,75.0,Germany,GER,2016,Rio de Janeiro,Badminton,Badminton Men's Singles,NaN,summer
271112,135547,Viktoriya Viktorovna Zyabkina,F,23.0,174.0,62.0,Kazakhstan,KAZ,2016,Rio de Janeiro,Athletics,Athletics Women's 100 metres,NaN,summer
271113,135547,Viktoriya Viktorovna Zyabkina,F,23.0,174.0,62.0,Kazakhstan,KAZ,2016,Rio de Janeiro,Athletics,Athletics Women's 200 metres,NaN,summer
271114,135547,Viktoriya Viktorovna Zyabkina,F,23.0,174.0,62.0,Kazakhstan,KAZ,2016,Rio de Janeiro,Athletics,Athletics Women's 4 x 100 metres Relay,NaN,summer
271115,135568,Olga Igorevna Zyuzkova,F,33.0,171.0,69.0,Belarus,BLR,2016,Rio de Janeiro,Basketball,Basketball Women's Basketball,NaN,summer

In [17]:
### confirm that you have the correct number of rows after the join.
### you can scroll up to count the number of entries in oly_w and oly_s.
### The totals should be equal to the value generated below
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 271116 entries, 0 to 271115
Data columns (total 14 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   ID            271116 non-null  int64
 1   Athlete Name  271116 non-null  str
 2   Sex           271116 non-null  str
 3   Age           261642 non-null  float64
 4   Height        210945 non-null  float64
 5   Weight        208241 non-null  float64
 6   Team          271116 non-null  str
 7   NOC           271116 non-null  str
 8   Year          271116 non-null  int64
 9   City          271116 non-null  str
 10  Sport         271116 non-null  str
 11  Event         271116 non-null  str
 12  Medal         39783 non-null   str
 13  Season        271116 non-null  str
dtypes: float64(3), int64(2), str(9)
memory usage: 29.0 MB

## Improving memory allocation

If we were working with a massive dataset, we'd want to find ways to improve processing power.

For example, the following columns have only a few values that repeat again and again as strings. This is highly inefficient.

- The "Season" column has "winter" and "summer",
- The "Medal" column only has "gold", "silver" and "bronze",
- "Gender" at this point in the Olympics only has "male" and "female".

One way to improve memory allocation is to take columns with that contain only a few data points and turn them into categories.

In [18]:
## you should see how "Season", "Medal" and "Gender" are all string objects.
## Note that memory usage: 29+ MB

### Convert to single column to category
```df["column_name"].astype("category")```

In [19]:
## convert gender to category
df["Sex"] = df["Sex"].astype("category")

In [20]:
## INFO
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 271116 entries, 0 to 271115
Data columns (total 14 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   ID            271116 non-null  int64
 1   Athlete Name  271116 non-null  str
 2   Sex           271116 non-null  category
 3   Age           261642 non-null  float64
 4   Height        210945 non-null  float64
 5   Weight        208241 non-null  float64
 6   Team          271116 non-null  str
 7   NOC           271116 non-null  str
 8   Year          271116 non-null  int64
 9   City          271116 non-null  str
 10  Sport         271116 non-null  str
 11  Event         271116 non-null  str
 12  Medal         39783 non-null   str
 13  Season        271116 non-null  str
dtypes: category(1), float64(3), int64(2), str(8)
memory usage: 27.1 MB

### Convert to multiple columns to category

 ```df[["column_name1", "column_name2]].astype("category")```

In [21]:
## convert medal and season  to catagory
df[["Medal", "Season"]] = df[["Medal", "Season"]].astype("category")

In [27]:
## See what the memory allocation is now using info()
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 271116 entries, 0 to 271115
Data columns (total 14 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   ID            271116 non-null  int64
 1   Athlete Name  271116 non-null  str
 2   Sex           271116 non-null  category
 3   Age           261642 non-null  float64
 4   Height        210945 non-null  float64
 5   Weight        208241 non-null  float64
 6   Team          271116 non-null  str
 7   NOC           271116 non-null  str
 8   Year          271116 non-null  int64
 9   City          271116 non-null  str
 10  Sport         271116 non-null  str
 11  Event         271116 non-null  str
 12  Medal         39783 non-null   category
 13  Season        271116 non-null  category
dtypes: category(3), float64(3), int64(2), str(6)
memory usage: 23.5 MB

# It should have dropped to 23.5MB.
That's a big descrease for just about 270,000 rows.

This would have an even bigger impact on larger datasets.

# Query to subset

Create smaller datasets with only the information you want

### Create a subset that holds the results from the Sochi Olympics

```df.query("ColumnName == 'some_value'")```

In [24]:
## return df that holds only Sochi data
df["City"].unique()
df.query("City == 'Sochi'")

,ID,Athlete Name,Sex,Age,Height,Weight,Team,NOC,Year,City,Sport,Event,Medal,Season
43673,16,Juhamatti Tapio Aaltonen,M,28.0,184.0,85.0,Finland,FIN,2014,Sochi,Ice Hockey,Ice Hockey Men's Ice Hockey,Bronze,winter
43674,126,Forough Abbasi,F,20.0,164.0,58.0,Iran,IRI,2014,Sochi,Alpine Skiing,Alpine Skiing Women's Slalom,NaN,winter
43675,145,Jeremy Abbott,M,28.0,175.0,70.0,United States,USA,2014,Sochi,Figure Skating,Figure Skating Men's Singles,NaN,winter
43676,145,Jeremy Abbott,M,28.0,175.0,70.0,United States,USA,2014,Sochi,Figure Skating,Figure Skating Mixed Team,Bronze,winter
43677,463,Agnese boltia,F,17.0,166.0,60.0,Latvia,LAT,2014,Sochi,Alpine Skiing,Alpine Skiing Women's Super G,NaN,winter
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48559,135485,Stepan Olegovich Zuyev,M,25.0,189.0,90.0,Russia,RUS,2014,Sochi,Alpine Skiing,Alpine Skiing Men's Slalom,NaN,winter
48560,135500,Kristaps Zvejnieks,M,21.0,185.0,87.0,Latvia,LAT,2014,Sochi,Alpine Skiing,Alpine Skiing Men's Giant Slalom,NaN,winter
48561,135500,Kristaps Zvejnieks,M,21.0,185.0,87.0,Latvia,LAT,2014,Sochi,Alpine Skiing,Alpine Skiing Men's Slalom,NaN,winter
48562,135570,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Individual",NaN,winter
48563,135570,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Team",NaN,winter

### Note the order of the single and double quotes:

If you open with double quotes, the inner quotes have to be single quotes:

```df.query("City == 'Sochi'")```

If you open with single quotes, the inner quotes have to be double quotes:

```df.query('City == "Sochi"')```


Using the same outer and inner quotes will break your code:
</br>
```df.query("City == "Sochi"") ## will break ```

In [25]:
## Store subset into dataframe called sochi_df
sochi_df = df.query("City == 'Sochi'")

**Syntax for querying multi-word column names:**

```dataframe.query('`column name` comparison_operator value')```

Note the opening and closing tick marks ``` ` ```

In [26]:
#will break
french_df = df.query('Team =='France'')

SyntaxError: invalid syntax. Perhaps you forgot a comma? (4289745905.py, line 2)

In [28]:
## query to return on french athletes
french_df = df.query("Team =='France'")
french_df

,ID,Athlete Name,Sex,Age,Height,Weight,Team,NOC,Year,City,Sport,Event,Medal,Season
6,2329,Louis Albert,M,25.0,NaN,NaN,France,FRA,1924,Chamonix,Ski Jumping,"Ski Jumping Men's Normal Hill, Individual",NaN,winter
11,4060,Georges Jules Andr,M,47.0,NaN,NaN,France,FRA,1924,Chamonix,Curling,Curling Men's Curling,Bronze,winter
19,7343,Klber Balmat,M,27.0,NaN,NaN,France,FRA,1924,Chamonix,Ski Jumping,"Ski Jumping Men's Normal Hill, Individual",NaN,winter
20,7343,Klber Balmat,M,27.0,NaN,NaN,France,FRA,1924,Chamonix,Nordic Combined,Nordic Combined Men's Individual,NaN,winter
24,10841,Georges Camille Berthet,M,20.0,NaN,NaN,France,FRA,1924,Chamonix,Military Ski Patrol,Military Ski Patrol Men's Military Ski Patrol,Bronze,winter
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
270385,129003,Marie Wattel,F,19.0,181.0,71.0,France,FRA,2016,Rio de Janeiro,Swimming,Swimming Women's 4 x 100 metres Medley Relay,NaN,summer
270695,132134,Isabelle Yacoubou-Dehoui,F,30.0,190.0,104.0,France,FRA,2016,Rio de Janeiro,Basketball,Basketball Women's Basketball,NaN,summer
270812,133031,Tony Victor James Yoka,M,24.0,200.0,105.0,France,FRA,2016,Rio de Janeiro,Boxing,Boxing Men's Super-Heavyweight,Gold,summer
270894,133577,Grce Zaadi Deuna,F,23.0,171.0,66.0,France,FRA,2016,Rio de Janeiro,Handball,Handball Women's Handball,Silver,summer
270972,134401,Mickal-Meba Zz,M,22.0,175.0,66.0,France,FRA,2016,Rio de Janeiro,Athletics,Athletics Men's 4 x 100 metres Relay,NaN,summer

## Filtering by dates

You'll learn more about date and time in the coming week. For now, please note how the ```Year``` column is a  ```int64``` object and NOT a ```datetime``` object. We can still work with it for our needs.

In [31]:
## GET INFO (ALSO EXPORTING FOR VIBE CODING FUNCTIONS)
df.info()
df.to_csv("df_olympics.csv", index = False)

<class 'pandas.DataFrame'>
RangeIndex: 271116 entries, 0 to 271115
Data columns (total 14 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   ID            271116 non-null  int64
 1   Athlete Name  271116 non-null  str
 2   Sex           271116 non-null  category
 3   Age           261642 non-null  float64
 4   Height        210945 non-null  float64
 5   Weight        208241 non-null  float64
 6   Team          271116 non-null  str
 7   NOC           271116 non-null  str
 8   Year          271116 non-null  int64
 9   City          271116 non-null  str
 10  Sport         271116 non-null  str
 11  Event         271116 non-null  str
 12  Medal         39783 non-null   category
 13  Season        271116 non-null  category
dtypes: category(3), float64(3), int64(2), str(6)
memory usage: 23.5 MB

In [34]:
## Find all the 1900 competitions
df_1900 = df[df['Year'] == 1900]
df_1900

,ID,Athlete Name,Sex,Age,Height,Weight,Team,NOC,Year,City,Sport,Event,Medal,Season
48944,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold,summer
48945,133,Franz Abb,M,NaN,NaN,NaN,Germany,GER,1900,Paris,Gymnastics,Gymnastics Men's Individual All-Around,NaN,summer
48946,150,Margaret Ives Abbott (-Dunne),F,23.0,NaN,NaN,United States,USA,1900,Paris,Golf,Golf Women's Individual,Gold,summer
48947,151,Mary Perkins Ives Abbott (Perkins-),F,42.0,NaN,NaN,United States,USA,1900,Paris,Golf,Golf Women's Individual,NaN,summer
48948,404,"Louis Grenville ""Lou"" Abell",M,15.0,NaN,NaN,Vesper Boat Club,USA,1900,Paris,Rowing,Rowing Men's Coxed Eights,Gold,summer
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50875,131733,William Hayden Wright,M,NaN,NaN,NaN,A North American Team,USA,1900,Paris,Polo,Polo Men's Polo,Bronze,summer
50876,133574,Henri Yvon,M,NaN,NaN,NaN,France,FRA,1900,Paris,Fencing,"Fencing Men's Foil, Masters, Individual",NaN,summer
50877,133574,Henri Yvon,M,NaN,NaN,NaN,France,FRA,1900,Paris,Fencing,"Fencing Men's epee, Masters, Individual",NaN,summer
50878,133807,Pyotr Antonovich Zakovorot,M,NaN,NaN,NaN,Russia,RUS,1900,Paris,Fencing,"Fencing Men's Sabre, Masters, Individual",NaN,summer
50879,134198,"Walter John ""Jack"" Zealley",M,NaN,NaN,NaN,Upton Park FC,GBR,1900,Paris,Football,Football Men's Football,Gold,summer

In [37]:
### return all the competitions between 1920 and 1950 (inclusive)
df_1920_1950_inc = df[(df['Year'] >= 1920) & (df['Year'] <= 1950)]
df_1920_1950_inc

,ID,Athlete Name,Sex,Age,Height,Weight,Team,NOC,Year,City,Sport,Event,Medal,Season
0,391,Clarence John Abel,M,23.0,185.0,102.0,United States,USA,1924,Chamonix,Ice Hockey,Ice Hockey Men's Ice Hockey,Silver,winter
1,992,Josef Adolf,M,25.0,NaN,NaN,Czechoslovakia,TCH,1924,Chamonix,Nordic Combined,Nordic Combined Men's Individual,NaN,winter
2,1077,Xavier Affentranger,M,26.0,NaN,NaN,Switzerland,SUI,1924,Chamonix,Ski Jumping,"Ski Jumping Men's Normal Hill, Individual",NaN,winter
3,1077,Xavier Affentranger,M,26.0,NaN,NaN,Switzerland,SUI,1924,Chamonix,Cross Country Skiing,Cross Country Skiing Men's 18 kilometres,NaN,winter
4,1077,Xavier Affentranger,M,26.0,NaN,NaN,Switzerland,SUI,1924,Chamonix,Nordic Combined,Nordic Combined Men's Individual,NaN,winter
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91447,135510,Jan Marcus Zwaan,M,22.0,NaN,NaN,Netherlands,NED,1948,London,Athletics,Athletics Men's 110 metres Hurdles,NaN,summer
91448,135511,"Johan Gerard ""Jo"" Zwaan",M,25.0,NaN,NaN,Netherlands,NED,1948,London,Athletics,Athletics Men's 100 metres,NaN,summer
91449,135511,"Johan Gerard ""Jo"" Zwaan",M,25.0,NaN,NaN,Netherlands,NED,1948,London,Athletics,Athletics Men's 4 x 100 metres Relay,NaN,summer
91450,135517,Fritz Zwazl,M,22.0,NaN,NaN,Austria,AUT,1948,London,Swimming,Swimming Men's 100 metres Backstroke,NaN,summer
91451,135534,"John Michael ""Jack"" Zwierewich",M,19.0,NaN,NaN,Canada,CAN,1948,London,Rowing,Rowing Men's Coxed Eights,NaN,summer

In [40]:
## Were there any games in 1950
df_1950games = df[df['Year'] == 1950]
were_there_games_in_1950 = not df_1950games.empty
were_there_games_in_1950

False

In [42]:
## return only Tennis competitions between 1920 and 1950 (inclusive)
df_tennis_1920_1950_inc = df[(df['Sport'] == 'Tennis') & (df['Year'] >= 1920) & (df['Year'] <= 1950)]
df_tennis_1920_1950_inc

,ID,Athlete Name,Sex,Age,Height,Weight,Team,NOC,Year,City,Sport,Event,Medal,Season
61094,2302,Pierre Henri Maurice Albarran,M,26.0,NaN,NaN,France-3,FRA,1920,Antwerpen,Tennis,Tennis Men's Doubles,Bronze,summer
61115,3034,Jos Mara Alonso de Areyzaga,M,30.0,NaN,NaN,Spain,ESP,1920,Antwerpen,Tennis,Tennis Men's Singles,NaN,summer
61116,3034,Jos Mara Alonso de Areyzaga,M,30.0,NaN,NaN,Spain-2,ESP,1920,Antwerpen,Tennis,Tennis Men's Doubles,NaN,summer
61117,3038,Manuel Alonso de Areyzaga,M,24.0,175.0,66.0,Spain,ESP,1920,Antwerpen,Tennis,Tennis Men's Singles,NaN,summer
61118,3038,Manuel Alonso de Areyzaga,M,24.0,175.0,66.0,Spain-2,ESP,1920,Antwerpen,Tennis,Tennis Men's Doubles,NaN,summer
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70549,134322,Ladislav emla,M,36.0,NaN,NaN,Czechoslovakia,TCH,1924,Paris,Tennis,Tennis Men's Singles,NaN,summer
70550,134322,Ladislav emla,M,36.0,NaN,NaN,Czechoslovakia-2,TCH,1924,Paris,Tennis,Tennis Men's Doubles,NaN,summer
70551,134376,Avgoustos Zerlentis,M,37.0,NaN,NaN,Greece,GRE,1924,Paris,Tennis,Tennis Men's Singles,NaN,summer
70552,134376,Avgoustos Zerlentis,M,37.0,NaN,NaN,Greece,GRE,1924,Paris,Tennis,Tennis Mixed Doubles,NaN,summer
70553,134376,Avgoustos Zerlentis,M,37.0,NaN,NaN,Greece,GRE,1924,Paris,Tennis,Tennis Men's Doubles,NaN,summer

In [43]:
## return only Women's Tennis competitions results
## between 1996 and 2018 inclusive
df_women_tennis = df[(df['Sport'] == 'Tennis') & (df['Sex'] == 'F')]
df_women_tennis
ans_6 = df[(df['Sport'] == 'Tennis') & (df['Sex'] == 'F') & (df['Year'] >= 1996) & (df['Year'] <= 2018)]

,ID,Athlete Name,Sex,Age,Height,Weight,Team,NOC,Year,City,Sport,Event,Medal,Season
49260,22925,Charlotte Reinagle Cooper (-Sterry),F,29.0,NaN,NaN,Great Britain,GBR,1900,Paris,Tennis,Tennis Women's Singles,Gold,summer
49261,22925,Charlotte Reinagle Cooper (-Sterry),F,29.0,NaN,NaN,Great Britain,GBR,1900,Paris,Tennis,Tennis Mixed Doubles,Gold,summer
49592,36538,Marguerite Fourrier,F,NaN,NaN,NaN,France,FRA,1900,Paris,Tennis,Tennis Women's Singles,NaN,summer
49656,40381,"Catherine Marie Blanche ""Katie"" Gillou (-Fenwick)",F,13.0,NaN,NaN,France,FRA,1900,Paris,Tennis,Tennis Mixed Doubles,NaN,summer
49843,55662,Georgina Frances Jones (-Walton),F,17.0,NaN,NaN,United States,USA,1900,Paris,Tennis,Tennis Women's Singles,NaN,summer
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
270690,132098,Xu Yifan,F,27.0,165.0,60.0,China-2,CHN,2016,Rio de Janeiro,Tennis,Tennis Women's Doubles,NaN,summer
271007,134544,Zhang Shuai,F,27.0,177.0,66.0,China,CHN,2016,Rio de Janeiro,Tennis,Tennis Women's Singles,NaN,summer
271008,134544,Zhang Shuai,F,27.0,177.0,66.0,China-1,CHN,2016,Rio de Janeiro,Tennis,Tennis Women's Doubles,NaN,summer
271039,134739,Zheng Saisai,F,22.0,170.0,62.0,China,CHN,2016,Rio de Janeiro,Tennis,Tennis Women's Singles,NaN,summer
271040,134739,Zheng Saisai,F,22.0,170.0,62.0,China-2,CHN,2016,Rio de Janeiro,Tennis,Tennis Women's Doubles,NaN,summer

In [45]:
## volleyball or rowing for only Male
df_vb_row_male = df[(df['Sport'].isin(['Volleyball', 'Rowing'])) & (df['Sex'] == 'M')]
df_vb_row_male

,ID,Athlete Name,Sex,Age,Height,Weight,Team,NOC,Year,City,Sport,Event,Medal,Season
48948,404,"Louis Grenville ""Lou"" Abell",M,15.0,NaN,NaN,Vesper Boat Club,USA,1900,Paris,Rowing,Rowing Men's Coxed Eights,Gold,summer
48963,3476,Max Heinrich Ammermann,M,21.0,NaN,NaN,Favorite Hammonia-3,GER,1900,Paris,Rowing,Rowing Men's Coxed Fours,Bronze,summer
48975,4343,Angot,M,NaN,NaN,NaN,Club Nautique de Dieppe-5,FRA,1900,Paris,Rowing,Rowing Men's Coxed Fours,NaN,summer
48980,5538,St George Ashe,M,28.0,NaN,NaN,Great Britain,GBR,1900,Paris,Rowing,Rowing Men's Single Sculls,Bronze,summer
49005,8065,Hermann Joseph Barrelet,M,20.0,NaN,NaN,France,FRA,1900,Paris,Rowing,Rowing Men's Single Sculls,Gold,summer
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
270943,134057,Anton Sergeyevich Zarutsky,M,30.0,195.0,94.0,Russia,RUS,2016,Rio de Janeiro,Rowing,Rowing Men's Coxless Fours,NaN,summer
270946,134081,Pawe Zatorski,M,26.0,184.0,73.0,Poland,POL,2016,Rio de Janeiro,Volleyball,Volleyball Men's Volleyball,NaN,summer
270952,134145,Ivan Zaytsev,M,27.0,204.0,100.0,Italy,ITA,2016,Rio de Janeiro,Volleyball,Volleyball Men's Volleyball,Silver,summer
271023,134647,Zhao Jingbin,M,26.0,185.0,72.0,China,CHN,2016,Rio de Janeiro,Rowing,Rowing Men's Lightweight Coxless Fours,NaN,summer
271072,134970,Mirosaw Zitarski,M,22.0,190.0,90.0,Poland,POL,2016,Rio de Janeiro,Rowing,Rowing Men's Quadruple Sculls,NaN,summer

## What year was women's boxing introduced to the olympics?

In [49]:
## find all the names of sports first just to confirm boxing
## does not appear in different names -- yes it does?
## how is boxing listed? -- as "Boxing"
df["Sport"].unique()

<StringArray>
[               'Ice Hockey',           'Nordic Combined',
               'Ski Jumping',      'Cross Country Skiing',
                   'Curling',                 'Bobsleigh',
       'Military Ski Patrol',            'Figure Skating',
             'Speed Skating',                  'Alpinism',
                  'Skeleton',             'Alpine Skiing',
                  'Biathlon',                      'Luge',
          'Freestyle Skiing', 'Short Track Speed Skating',
              'Snowboarding',                    'Tennis',
                 'Athletics',                  'Swimming',
                'Gymnastics',                  'Shooting',
                   'Cycling',                   'Fencing',
             'Weightlifting',                 'Wrestling',
                'Tug-Of-War',                      'Golf',
                    'Rowing',                     'Rugby',
                   'Sailing',                  'Football',
                   'Cricket',                'Water Polo',
             'Equestrianism',                   'Croquet',
                   'Archery',                      'Polo',
             'Basque Pelota',                  'Lacrosse',
                    'Boxing',                    'Diving',
                     'Roque',                    'Hockey',
                  'Racquets',              'Motorboating',
              'Jeu De Paume',          'Art Competitions',
         'Modern Pentathlon',                'Basketball',
                  'Handball',                  'Canoeing',
               'Aeronautics',                'Volleyball',
                      'Judo',       'Rhythmic Gymnastics',
     'Synchronized Swimming',              'Table Tennis',
                 'Badminton',                  'Baseball',
          'Beach Volleyball',                  'Softball',
                 'Taekwondo',                 'Triathlon',
              'Trampolining',              'Rugby Sevens']
Length: 66, dtype: str

### When did boxing first appear as a sport in which women competed at the olympics?

In [53]:
## query for boxing and women
## store in new df
df_women_boxing = df[(df['Sport'] == 'Boxing') & (df['Sex'] == 'F')]
df_women_boxing_sort = df_women_boxing.sort_values(by='Year', ascending=True)
df_women_boxing_sort.head(20)

,ID,Athlete Name,Sex,Age,Height,Weight,Team,NOC,Year,City,Sport,Event,Medal,Season
244598,832,Nicola Virginia Adams,F,29.0,164.0,51.0,Great Britain,GBR,2012,London,Boxing,Boxing Women's Flyweight,Gold,summer
252033,79355,Karolina Michalczuk,F,32.0,164.0,51.0,Poland,POL,2012,London,Boxing,Boxing Women's Flyweight,NaN,summer
252877,87919,Sofya Albertovna Ochigava,F,25.0,170.0,60.0,Russia,RUS,2012,London,Boxing,Boxing Women's Lightweight,Silver,summer
252896,88189,Edith Ogoke,F,21.0,NaN,75.0,Nigeria,NGR,2012,London,Boxing,Boxing Women's Middleweight,NaN,summer
253072,90065,Mahjouba Oubtil,F,29.0,NaN,60.0,Morocco,MAR,2012,London,Boxing,Boxing Women's Lightweight,NaN,summer
253469,94145,Stoyka Zhelyazkova Petrova,F,26.0,163.0,51.0,Bulgaria,BUL,2012,London,Boxing,Boxing Women's Flyweight,NaN,summer
253752,97059,Alexis Pritchard,F,28.0,178.0,NaN,New Zealand,NZL,2012,London,Boxing,Boxing Women's Lightweight,NaN,summer
253882,98330,Maroua Rahali,F,24.0,168.0,NaN,Tunisia,TUN,2012,London,Boxing,Boxing Women's Flyweight,NaN,summer
254016,99913,Ren Cancan,F,24.0,167.0,51.0,China,CHN,2012,London,Boxing,Boxing Women's Flyweight,Silver,summer
254563,106220,Yelena Vladimirovna Savelyeva,F,28.0,168.0,51.0,Russia,RUS,2012,London,Boxing,Boxing Women's Flyweight,NaN,summer
254892,109724,Claressa Maria Shields,F,17.0,175.0,75.0,United States,USA,2012,London,Boxing,Boxing Women's Middleweight,Gold,summer
255281,113783,Mary Spencer,F,27.0,180.0,73.0,Canada,CAN,2012,London,Boxing,Boxing Women's Middleweight,NaN,summer
255782,118917,"Kathleen ""Katie"" Taylor",F,26.0,165.0,60.0,Ireland,IRL,2012,London,Boxing,Boxing Women's Lightweight,Gold,summer
256005,121172,Nadezhda Viktorovna Torlopova,F,33.0,175.0,75.0,Russia,RUS,2012,London,Boxing,Boxing Women's Middleweight,Silver,summer
256223,123331,"Quanita ""Queen"" Underwood",F,28.0,165.0,60.0,United States,USA,2012,London,Boxing,Boxing Women's Lightweight,NaN,summer
256573,126863,Yelena Vstropova,F,23.0,174.0,NaN,Azerbaijan,AZE,2012,London,Boxing,Boxing Women's Middleweight,NaN,summer
251762,76497,Erica dos Santos Matos,F,29.0,162.0,51.0,Brazil,BRA,2012,London,Boxing,Boxing Women's Flyweight,NaN,summer
251675,75428,Savannah Rose Dee Marshall,F,21.0,181.0,75.0,Great Britain,GBR,2012,London,Boxing,Boxing Women's Middleweight,NaN,summer
256607,127225,Marina Ivanovna Volnova,F,22.0,170.0,NaN,Kazakhstan,KAZ,2012,London,Boxing,Boxing Women's Middleweight,Bronze,summer
251080,69416,Li Jinzi,F,22.0,176.0,75.0,China,CHN,2012,London,Boxing,Boxing Women's Middleweight,Bronze,summer

### How many values in a column?

## Counting

- The ```sum``` adds up all the values in a dataset, to give you the total amount.

- The ```count``` tells you how many items of particular values exist in a dataset. It doesn't care about the values themselves, just the number of entries.

We use the ```.value_counts()``` method:

```df_name["column_name"].value_counts()```

### Summer v. Winter

How many athletes participated in the summer games v. the winter games?

In [67]:
## total number of athletes
total_s_athletes = dfs['ID'].nunique()
total_s_athletes

116776

In [68]:
total_w_athletes = dfw['ID'].nunique()
total_w_athletes

18958

In [69]:
s_vs_w = f"There have been {total_s_athletes} athletes who have competed in summer olympics, while only {total_w_athletes} athletes have competed in winter olympics."
print(s_vs_w)

There have been 116776 athletes who have competed in summer olympics, while only 18958 athletes have competed in winter olympics.

### ```value_counts()``` parameter

By default, it is ```.value_counts(normalize = False)```

This gives you want we calculated above

But ```.value_counts(normalize = True)``` returns  proportions (fractions of the total).

In [ ]:
## get as proportion

In [ ]:
## convert to you want it as a percentage

In [ ]:
## subset data to hold only medals

In [ ]:
## what is the total medal count for winter v. summer?

# DRY

Do not repeat yourself

In [ ]:
##get list of uniques

In [ ]:
# target_medals = ["Gold", "Silver", "Bronze"]

In [ ]:
## get head

In [ ]:
## call winners

In [ ]:
## what is the total medal count for winter v. summer?

## How many medals were handed out at each olympics between 1896 and 2014?

Show the result from highest to lowest.

In [81]:
## how many medals were handed out at each olympics?
## show the result in descending order
df_medals = df.dropna(subset=['Medal'])
medals_by_count = df_medals.groupby(['Year', 'Season'])['Medal'].count().sort_values(ascending=False)
medals_by_count

Year  Season
2008  summer    2048
2016  summer    2023
2000  summer    2004
2004  summer    2001
2012  summer    1941
1996  summer    1842
1992  summer    1712
1988  summer    1582
1984  summer    1476
1980  summer    1384
1976  summer    1320
1920  summer    1308
1972  summer    1215
1968  summer    1057
1964  summer    1029
1912  summer     941
1936  summer     917
1960  summer     911
1952  summer     897
1956  summer     893
1948  summer     852
1924  summer     832
1908  summer     831
1928  summer     734
1932  summer     647
1900  summer     604
2014  winter     597
2006  winter     526
2010  winter     520
1904  summer     486
2002  winter     478
1906  summer     458
1998  winter     440
1994  winter     331
1992  winter     318
1988  winter     263
1984  winter     222
1980  winter     218
1976  winter     211
1972  winter     199
1968  winter     199
1964  winter     186
1956  winter     150
1960  winter     147
1896  summer     143
1952  winter     136
1948  winter     135
1924  winter     130
1936  winter     108
1932  winter      92
1928  winter      89
Name: Medal, dtype: int64

In [85]:
## how many medals were handed out at each olympics each
## year from as recent as possible down to 1896.
medals_by_year = df_medals.groupby(['Year', 'Season'])['Medal'].count().reset_index().sort_values(by='Year', ascending=False)
medals_by_year

    Year  Season  Medal
50  2016  summer   2023
49  2014  winter    597
48  2012  summer   1941
47  2010  winter    520
46  2008  summer   2048
45  2006  winter    526
44  2004  summer   2001
43  2002  winter    478
42  2000  summer   2004
41  1998  winter    440
40  1996  summer   1842
39  1994  winter    331
38  1992  winter    318
37  1992  summer   1712
36  1988  winter    263
35  1988  summer   1582
34  1984  winter    222
33  1984  summer   1476
32  1980  winter    218
31  1980  summer   1384
30  1976  winter    211
29  1976  summer   1320
28  1972  winter    199
27  1972  summer   1215
26  1968  winter    199
25  1968  summer   1057
24  1964  winter    186
23  1964  summer   1029
22  1960  winter    147
21  1960  summer    911
20  1956  winter    150
19  1956  summer    893
18  1952  winter    136
17  1952  summer    897
16  1948  winter    135
15  1948  summer    852
13  1936  summer    917
14  1936  winter    108
12  1932  winter     92
11  1932  summer    647
10  1928  winter     89
9   1928  summer    734
8   1924  winter    130
7   1924  summer    832
6   1920  summer   1308
5   1912  summer    941
4   1908  summer    831
3   1906  summer    458
2   1904  summer    486
1   1900  summer    604
0   1896  summer    143

In [73]:
## top 10 count of gold medals by country
df_gold = df[df['Medal'] == 'Gold']
top_10_gold = df_gold['NOC'].value_counts().head(10)
top_10_gold

NOC
USA    2638
URS    1082
GER     745
GBR     678
ITA     575
FRA     501
SWE     479
CAN     463
HUN     432
GDR     397
Name: count, dtype: int64

In [88]:
## count of gold medals by country by percent
## only gold winner df
gold_percent = (df_gold['NOC'].value_counts(normalize=True)*100)
gold_percent

NOC
USA    19.727789
URS     8.091535
GER     5.571343
GBR     5.070296
ITA     4.300030
         ...
BRN     0.007478
KOS     0.007478
TJK     0.007478
PUR     0.007478
SGP     0.007478
Name: proportion, Length: 109, dtype: float64

In [89]:
## as percent -- wasn't sure what this was refering to, I did percent of gold out of all medals for each country
total_medals = df_medals['NOC'].value_counts()

In [80]:
## how many times did Russia win the gold?
russia_golds = len(df_gold[df_gold['NOC'] == 'RUS'])
russia_golds

390